### PR TITLE
Add 'tablesort.css' to 'main' property in bower.json

### PR DESCRIPTION
**Pull request by dstulle**
Hello,

I added the css file to the main property so tools like [wiredep](https://github.com/taptapship/wiredep). Will recognize it and use it.

### CODE REVIEW

**Comment by likerRr** [comment]
Hi, would be great if you accept this PR, cause I also use `wiredep` and it can't recognize `tablesort.css` until it isn't in bower's main section. Thx!

**Comment by mattiash** [comment]
I am a bit reluctant to merging this. The reason is that I don't really consider tablesort.css as part of tablesort. I don't want to make styling of the table a part of the tablesort "project", since I have no intention of telling people how to style their tables. So my question is "are you really using tablesort.css in your projects? Don't you have a separate stylesheet anyway?

That being said, I suppose merging this does no harm since it is up to anyone to decide if they want to reference tablesort.css anyway.

**Comment by likerRr** [comment]
@mattiash what you wrote makes sense. So, probably I'll do what you suggested and just will copy paste styles from `tablesort.css` into separate stylesheet until we don't have specific requirements for design. Thx

**Comment by dstulle** [comment]
I would consider a default style a part of the project, because without any style the look and feel would not suggest any "klickability" or indicate the "sorting-order" of the table columns.

But either way, if using wiredep one can include or exclude the style using [bower-overrides](https://github.com/taptapship/wiredep#bower-overrides).

**Comment by likerRr** [comment]
@mattiash thank you :+1:

**Pull request merged**
