### PR TITLE
Add ability to specify a custom sorting function for a column

### PR DESCRIPTION
**Pull request by tbroadley**

### CODE REVIEW

**Comment by mattiash** [comment]
Your patch sounds reasonable, but unfortunately it no longer applies cleanly. Please fix that (and maybe PR-73 at the same time since they are bound to be in conflict with this one?) and then I can merge it.

**Comment by SergeyCherman** [comment]
@tbroadley Can you resubmit? Your changes are mostly still good, just don't need the default compare anymore. If you don't have time I'll make your changes on top of master and submit the PR.

**Comment by tbroadley** [comment]
@SergeyCherman Sure, I'll fix the merge conflicts right now.

**Comment by tbroadley** [comment]
@SergeyCherman Could you please take another look at these changes?

**Comment by SergeyCherman** [comment]
Looks good to me, thanks for the quick turn around!

**Comment by SergeyCherman** [comment]
@mattiash can you take a look and consider a merge and version bump?

**Pull request merged**
